baseURL = 'https://nikrad.github.io/blog-demo/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'typo'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
homeCollection = 'posts'
hideHeader = false
showFooter = false
footerContent = "Your **custom** md `footer`"

[params.breadcrumbs]
enabled = false
showCurrentPage = true
home = "~"

